### ISSUE TITLE
Dynamic module imports failing on Windows OS

### ISSUE THREAD

**Issue by EBay1992** [ehsanagh/nodejs-backend-structure-modular-JS#25]
There is some inconsistency in the functionality of ES modules across different operating systems. You can read about this inconsistency here: https://github.com/nodejs/node/issues/31710#issuecomment-587434048. It is important to make this functionality consistent across all operating systems.

Currently, there is a schema problem when Node.js tries to import a file on Windows, which leads to the following error: code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'.

To address this issue, we need to make the functionality of ES modules consistent across all operating systems.

**Comment by ethyaan** [comment]
Merged
